Revert "Revert "ASoC: Add SPDIF DAI format""
This reverts commit 203815f6b096465caf19acd913e0743f596e388a.

Fix compilation error:
  sound/soc/soc-core.c:3697:14: error: 'SND_SOC_DAIFMT_SPDIF' undeclared