dmaengine: xilinx_dma: Move enum xdma_ip_type to driver file
commit 9d007340cd773663aa3e018a46e2c8226eaab1ab did the right thing
but my merge made things fail.

Put the definition back, and while at it remove the useless comments.

Fix build fail:
  error: field 'dmatype' has incomplete type
  error: 'XDMA_TYPE_VDMA' undeclared